OWNERS
=> OWNERS: add bentheelder as approver

README.md, RELEASE.md, SECURITY_CONTACTS
- update README with non-boilerplate content
- remove boilerplate RELEASE.md that doesn't apply here currently
- add myself to SECURITY_CONTACTS, I'm in OWNERS and already have agreed to the terms elsewhere
this PR is not particularly important, but doubles to test #7 🙃
=> cleanup boilerplate files slightly

cmd/archeio/main.go
address https://github.com/kubernetes-sigs/oci-proxy/pull/14#discussion_r799066480
=> address logging nits

cmd/archeio/main.go
=> drop v1 support

.github/workflows/archeio-unit-test.yaml, cmd/archeio/main_test.go
Adds function unit tests for archeo
=> Add unit tests

Makefile, cloudbuild.yaml, hack/make-rules/deploy.sh
Related: https://github.com/kubernetes/k8s.io/issues/3577
=> Add auto-deploy to CloudRun regions

hack/tools/go.mod, hack/tools/go.sum
xref: https://github.com/golangci/golangci-lint/issues/2649
=> enable staticcheck in go1.18

cmd/archeio/main_test.go
TODO: get a linter going for this 
(low prio: ... we should review for this and we shouldn't have all that many more source files here, I have a PR coming to finish implementing redirection based on client IP)
=> add missing copyright header

cmd/archeio/README.md
clarifying some things, e.g. a lot of folks seem to be missing the "join the mailinglist" part and my inbox misses most of those. so let's add some details that aren't tucked away in the doc as well.
=> add some more details to README.md

cmd/archeio/app/handlers.go
For now redirect to a place holder URL (github repo for this service)
Signed-off-by: Davanum Srinivas <davanum@gmail.com>
=> Redirect to a placeholder URL about this service

cmd/archeio/app/handlers_test.go
forgot to push commit for test case
Signed-off-by: Davanum Srinivas <davanum@gmail.com>
=> test case for root url redirection

hack/make-rules/deploy.sh
=> Remove shellcheck comment

cmd/archeio/app/clientip.go, cmd/archeio/app/clientip_test.go, cmd/archeio/app/handlers.go
=> fix bugs in GetClientIP and MakeHandlers

cmd/archeio/app/clientip.go, cmd/archeio/app/clientip_test.go
=> add cloud run bug quirks-mode to getClientIP

cmd/archeio/app/handlers.go
This reverts commit afe5f2d0fb43ec458644933ea905140c81e4daff. / https://github.com/kubernetes-sigs/oci-proxy/pull/61
=> Revert "REVERT ME: debug why we're not redirecting kops to S3"

cmd/archeio/README.md, cmd/archeio/app/handlers.go, cmd/archeio/docs/request-handling.md
=> document request handling flow

cmd/archeio/README.md, cmd/archeio/docs/testing.md
=> document testing

cmd/archeio/app/handlers.go, cmd/archeio/app/handlers_test.go
=> Return temporary redirects instead of permanent ones

cmd/archeio/app/handlers.go
=> update the / redirection

cmd/archeio/app/handlers.go, cmd/archeio/app/handlers_test.go, cmd/archeio/main.go
Fixes #80
/cc @dims @ameukam 
~~Arnaud, we need to modify the sandbox instance of oci-proxy and set `SERVE_IMAGES_FROM_AWS` to `true`~~
=> Feature gate serving AWS S3 blobs from oci-proxy

cmd/archeio/main.go
Fixes: #83 
/cc @BenTheElder 
How would I go about optimising https://github.com/kubernetes-sigs/oci-proxy/pull/88/files#r929468837 ?
=> Fix infoURL

hack/make-rules/deploy.sh
Ensure oci-proxy will be deployed to the Tiers 1 regions of Cloud Run
=> Ensure deployment to Tier1 regions

go.mod, go.sum
=> Bump klog to latest

hack/make-rules/deploy.sh
Switch archeio to use regional AR container repositories.
Also remove incorrect Cloud Run region.
=> Use artifact registry for sandbox

cmd/archeio/app/clientip.go, cmd/archeio/app/clientip_test.go
... checked back up on this bug, it's fixed. 
per the issue tracker the fix was done rolling out in july, so we don't need the quirks-mode codepath anymore.
=> drop cloud run bug handling, as the bug has been fixed since july

cmd/archeio/app/handlers.go, cmd/archeio/app/handlers_test.go, cmd/archeio/main.go
we're stably serving AWS clients from s3 and we can simplify this code
=> remove s3 featuregate

README.md
=> set expectations clearly

README.md
=> clarify stability documentation, link to blogpost

cmd/geranos/main.go, cmd/geranos/s3uploader.go
this should cut down the log size dramatically, we can do more later
=> add a progress logging TODO and move layer logging to higher verbosity

cmd/geranos/walkimages.go
to match the rclone job, and focus on replacing it.
=> don't upload config layers for now

cmd/geranos/walkimages.go
xref #153 
this is a quick patch, it's not the end-game.
=> reduce geranos concurrency

README.md, cmd/archeio/README.md
ref #152, https://github.com/kubernetes/k8s.io/issues/4872#issuecomment-1461294540
=> Docs updates

cmd/geranos/main.go, cmd/geranos/ratelimitroundtrip.go
tiny little cleanup after reviewing this code while writing a modified version suitable for kpromo
=> simplify ratelimitroundtripper

debugging.md
Add document to help customers debug issues with registry.k8s.io
=> Add debugging issues with registry.k8s.io document

.github/ISSUE_TEMPLATE/issue.yaml
Issue template to collect informations for debugging
=> Add issue template

cmd/archeio/README.md
We've changed slightly since this was last updated, notably #147. 
We also no longer front GCR but AR instead as relatively drop-in compatible vs GCR.
The request handling docs have still been up to date, but not this one.
I've generalized the approaches a bit so we should need less updates in the future.
=> refresh archeio docs to current details

docs/mirroring/README.md
https://github.com/kubernetes/registry.k8s.io/pull/201/files#r1148125732
=> mirroring nit

docs/mirroring/README.md
this will be particularly useful when we have more options
=> add links to skip ahead below each mirroring option

docs/mirroring/README.md, docs/mirroring/cluster-api.md
This PR adds mirroring instructions for Cluster API.
=> mirroring instructions for Cluster API

hack/make-rules/deploy.sh
tiny follow-up to #210 to help debugging.
Holding until we fix the terraform IAM rules, then we can merge this and test.
/hold
=> log terraform command

hack/make-rules/deploy.sh
TODO: probably revert the entire prior commit instead
=> don't set quota-project

cmd/archeio/main_test.go
=> use pull+validate instead of pull cmd

cmd/archeio/internal/app/buckets_integration_test.go, pkg/net/cloudcidrs/ipmapper.go
should help prevent adopting unconfigured buckets
=> test that all configured buckets serve a sample blob

cmd/archeio/internal/app/buckets.go, cmd/archeio/internal/app/buckets_test.go
=> cleanup effectively external AWS region mapping

cmd/geranos/s3uploader.go
just log the key, it has enough context as to layer vs manifest
tiny follow-up for #248 
cc @ameukam
=> nit: shared log message

cmd/geranos/main.go
this was messed up in rebasing #248
=> geranos: return err and don't double log "Done!"

docs/mirroring/README.md
Since there's already a handy guide, let's link out to it!
=> document ECR pull-through cache option

docs/mirroring/README.md
tiny fix for https://github.com/kubernetes/registry.k8s.io/pull/268/files#r1362895283
=> correct heading level for ECR
