Makefile, cloudbuild.yaml, hack/make-rules/images.sh
... using `make push-images`
will push `gcr.io/k8s-staging-infra-tools/archeio:v$date-$sha`
`make images` will build to a tarball under `bin/archeio.tar`
=> make image publishable with automatic date-sha tag

hack/make-rules/images.sh, hack/make-rules/verify.sh, hack/tools/ci-install-shellcheck.sh
- fix paths in verify.sh after refactoring repo layout in previous PRs
- add a script to install shellcheck in CI matching the desired version used in the shellcheck script, so we can DRY that out and just use the golang image for all presubmits
- fix minor shellcheck error that slipped through because we don't have CI enabled yet
xref #7
=> fixes for enabling CI

cmd/archeio/main.go, go.mod, go.sum
preparing for registry.k8s.io fqdn to serve *just* a redirect.
- drop unneeded logic for now
- switch logging to klog, move request logging to non-default log level (we're going to log a LOT of lines if we don't do this)
=> switch to klog, simplify for pure redirect iteration

hack/images/default-sandbox.yaml
Make registry-sandbox.k8s.io the default registry for some e2e tests.
=> Add custom registries for e2e tests.

cmd/archeio/main.go
- protect against slowloris attacks by setting a read timeout that will close inactive connections , see https://groups.google.com/g/golang-nuts/c/MFZd6b8zQTQ/m/ISD96eyXtD4J
- implement graceful shutdown
=> Slowloris and graceful shutdown

cmd/archeio/main.go
=> support overriding upstream

pkg/net/cidrs/triemap.go, pkg/net/cidrs/triemap_test.go
just to be on the safe side. coverage was good before at 94% for triemap.go and 100% for the rest.
=> increase pkg/net/cidrs unit test coverage to 100%

cmd/archeio/app/handlers.go, hack/make-rules/deploy.sh
=> improve logging

cmd/archeio/app/handlers.go
I suspect we should not stay in the business of logging client IPs even with few people having access.
But this should *only* be deployed to the sandbox instance, which is not advertised to end users, only CI, and something is up there. Need to get some real data to debug. https://github.com/kubernetes-sigs/oci-proxy/pull/60#issuecomment-1105771135
=> REVERT ME: debug why we're not redirecting kops to S3

cmd/archeio/app/buckets.go, cmd/archeio/app/buckets_integration_test.go, cmd/archeio/app/buckets_test.go, cmd/archeio/app/handlers.go, cmd/archeio/app/handlers_test.go
The test bucket we have is a one-off sync and cannot be guaranteed to have all layers present.
This caused issues with our test job right after implementing redirect-to-s3 when kops started using an image we didn't have synced into the test s3 bucket. 
https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/e2e-kops-grid-gcr-mirror-canary/1517823558204526592
... so for the sake of development, I implemented checking if the layer actually exists.
Each AWS bucket can handle 5,500s HEAD RPS without sharding the bucket key prefix, if we need more we can implement key prefix, or we can institute caching in the OCI proxy. There appears to be no client rate limit, just the bucket scaling.
https://docs.aws.amazon.com/AmazonS3/latest/userguide/optimizing-performance.html
If for any reason we can't …
=> HEAD check and fallback if S3 is missing layers

cmd/archeio/app/buckets.go, cmd/archeio/app/buckets_integration_test.go, cmd/archeio/app/handlers.go, cmd/archeio/app/handlers_test.go
follow up to #66 
NOTE: this is a very naive (but should be reasonably fast) cache with **no eviction**. This is fine because we've selected 10 buckets https://github.com/kubernetes-sigs/oci-proxy/issues/39#issuecomment-1085230292 and there are approximately 97,000 blobs, with hashes being 64 bytes we can cache in approximately 10 * 100,000 * 64 bytes AKA 64 MB *even if* we actually observe _all_ keys in _all_ buckets for the lifecycle of the container, which is not remotely likely (consider e.g. that requests should be routed to the nearest cloud run instance, in addition to number of containers being scaled up/down).
=> cache bucket HEAD requests

cmd/archeio/app/buckets.go, hack/make-rules/deploy.sh
... so we can more easily determine if this is occurring
I see some very fast (1ms) redirect-to-s3 handling occurring sometimes, but let's make it clear.
=> log cache hits

cmd/archeio/app/handlers.go, cmd/archeio/app/handlers_test.go
part of #77 
I think we could instead serve 401 and craft an appropriate `Www-Authenticate: Bearer realm` header that includes the scope (unlike GCR, which lets the client determine it based on the repo it parses in the image name), but that's more complex and unnecessary.
Our target use case involves publicly readable registries, and GCR public read is *really* public read, you don't need to present an auth token for any of the API calls.
=> serve 200 OK for /v2/ API check

cmd/archeio/app/handlers.go, cmd/archeio/app/handlers_test.go, cmd/archeio/docs/request-handling.md
Fixes #81 
- Add `/privacy` endpoint  to `handlers.go` to serve LF privacy policy page.
- Add new endpoint to test case in `handlers_test.go`.
- Update request-handling.md text and chart flow.
=> Add endpoint to serve LF privacy page

cmd/archeio/app/buckets.go, cmd/archeio/app/handlers_test.go
Once the buckets have been synced, use the production S3 bucket URLs
Depends on: https://github.com/cncf-infra/aws-infra/issues/4, https://github.com/kubernetes/k8s.io/issues/3623
=> Update AWS region to S3 url to use production buckets

hack/make-rules/deploy.sh
Fix incorrect GCP regions for oci-proxy in the sandbox env.
=> Fix GCP regions

README.md, cmd/archeio/app/buckets_test.go, cmd/archeio/app/handlers.go, cmd/archeio/main.go, cmd/archeio/main_test.go, go.mod, hack/make-rules/test.sh, hack/tools/go.mod, pkg/net/cidrs/aws/mapper.go, pkg/net/cidrs/aws/mapper_test.go
reflecting repo move from kubernetes-sigs/oci-proxy to kubernetes/registry.k8s.io
=> rename sigs.k8s.io/oci-proxy => k8s.io/registry.k8s.io

hack/make-rules/deploy.sh
Follow-up of:
- https://github.com/kubernetes/k8s.io/pull/4258
Ensure same Cloud Run locations in production are the same in the sandbox environment.
=> Add more regions for sandbox environments

hack/make-rules/deploy.sh
@ameukam and I have been load testing and tuning in a staging region, in particular we should roll these options out widely:
- GOMAXPROCS to match the cores set in cloud run, to inform the go scheduler (which is not aware of containers let alone dynamic throttling, during request serving available CPU should match that configured and GOMAXPROCS should be set to match this)
- container concurrency up to 1000 (max) from 10 (this is how many requests one container instance will be allowed to handle concurrently, autoscaling more instances handles more)
=> set container conurrency and GOMAXPROCS

hack/make-rules/deploy.sh
Follow-up of https://github.com/kubernetes/registry.k8s.io/pull/112.
The `--update-env-vars` subcommand supports only a list of key-value pairs.
=> fix deploy parameter script

README.md
this is essentially a TLDR of the motivation from the existing doc, and a mention of the privacy policy.
this should let us start to redirect registry.k8s.io/ to the current repo docs instead of the "new url" doc (which captures the registry move as planned in a point in time, but may fall out of date more easily)
next up: change the `/` redirect in cmd/archeio
=> add some background details, and a note about privacy.

cmd/archeio/main.go
- Update info URL to point here. 
- I've done a docs sweep and we have current docs here that also link out to the other docs. More importantly we'd like people to file issues here if they're filing one, so those of us with access to fix the infra see them immediately with high signal : noise ratio (IE I watch this repo and unlike k8s.io repo the issues are very specific to this project)
- Update default registry endpoint config to point to artifact registry
- We can't keep using k8s.gcr.io (we are not in production anyhow) because soon it will redirect to us ... so use one of the AR regions. I chose us-central1 because prow.k8s.io is primarily there.
=> update default URLs

cmd/archeio/app/buckets.go, cmd/archeio/app/buckets_test.go, cmd/archeio/app/handlers_test.go
This ensure we're not routing traffic from Asia to the US ...
The mapping is from https://github.com/kubernetes/registry.k8s.io/issues/72#issue-1225709110
Initial commit _should fail_ CI, because that mapping is actually missing regions. Will follow up with adding those regions.
=> map to nearest AWS regions as previously proposed

cmd/archeio/app/handlers.go, pkg/clientip/clientip.go, pkg/clientip/clientip_test.go
for reuse by porche.
I almost put this in a package called `cloudrun`, because it's hard to fully generalize this method without making it much more complex and inefficient and it's unclear that we should be prioritizing arbitrary network topologies, versus just implementing specific ones as needed.
currently we assume this is either local HTTP testing in-memory, or else serving in cloud-run, where we can make assumptions about header availability and content.
originally I just didn't export this, to revisit later, but we'll have the same issue in porche
=> export getClientip as pkg/clientip.Get

hack/make-rules/shellcheck.sh
The shellcheck script defines REPO_ROOT but then uses KUBE_ROOT.
=> shellcheck: Fix undefined var

pkg/clientip/clientip.go, pkg/clientip/clientip_test.go
I thought this was not working correctly because of IPv6, it turned
out it was not working because I was trying to hit the CloudRun
endpoint directly.  Added some test coverage to prove that it works
and document this.
=> clientip: Add tests for IPv6

README.md
I couldn't find these docs at all, someone who publishes images kindly linked me to them (/ht @dgrisonnet).
This repo was the first place I checked for documentation, since I thought registry.k8s.io was replacing k8s.gcr.io. https://registry.k8s.io redirected to this repo which only discusses the proxy implementation and not the registry itself.
=> Add readme link to doc for publishing images

hack/tools/sync-to-s3.sh
/cc @BenTheElder 
I copied over the script and changed the bucket name and script name.
/hold
I need an image to be pushed to `gcr.io/k8s-artifacts-prod` first and complete the initial sync at https://github.com/kubernetes/test-infra/pull/28652
=> Copy sync script over and use the bucket backing `gcr.io/k8s-artifacts-prod`

cmd/geranos/main.go, cmd/geranos/s3uploader.go, cmd/geranos/walkimages.go
couple quick follow-ups that should be enough to get a test job running:
make dry-run configurable
throttle concurrency more ref #153 
fix s3 bucket / keys
skip existing layers by default
=> iterate on geranos MVP

cmd/geranos/main.go, cmd/geranos/ratelimitroundtrip.go, cmd/geranos/s3uploader.go, cmd/geranos/schemav1.go, cmd/geranos/walkimages.go
more complete and invasive version of #165 
worth noting: 
> In most cases, a single HTTP request or API call counts as a single request. However, some operations count as multiple requests. For example, a batch request like ImportAptArtifacts might charge quota for each item in the batch. A Docker pull or push usually makes multiple HTTP requests, so quota is charged for each request.
https://cloud.google.com/artifact-registry/quotas
=> rate limit all AR API calls

cmd/archeio/app/handlers.go, cmd/archeio/app/handlers_test.go
cc @jonjohnsonjr
pros:
- _catalog is non-portable, not supporting it leaves us more flexibility in what registry we depend on
- _catalog is scoped to a registry host, not a repository
cons:
- _catalog is useful, implementing it would be more helpful (but also then we need to continue to support it...)
I think blocking the broken call (we redirect to a path prefixed _catalog which won't work anywhere) is better than leaving a broken one. We can continue discussing potentially implementing in the meantime.
=> reject requests for /v2/_catalog

cmd/geranos/main.go
ref #166 #153 
This is working fine now, but a bit slower than desirable.
I'm going to work on other improvements, but in the meantime we might as well push closer to the rate limit and reduce the sync time hit (~13m => ~1h30m).
=> increase geranos registry rate limit

cmd/archeio/app/handlers.go, cmd/archeio/app/handlers_test.go, cmd/geranos/s3uploader.go
A bit of future-proofing. 
As-is we'd have just redirected to the upstream registry for all non-sha256 blobs, but after this change we should still redirect to S3 if the blob is available.
geranos should already be able to upload arbitrary digest keys, though it can only instruct S3 to integrity check uploads with sha256 currently.
=> archeio: support blob digest algorithms other than sha256

cmd/archeio/README.md, cmd/archeio/docs/request-handling.md
- We should discuss the current design before the original design
- Clarifying that you *must* join the mailinglist to access the original design sketch Google doc, still getting a lot of requests for this doc and this is the only place we currently link it AFAIK. Also clarifying that it's *not* current and the design has evolved, and outlining how that has evolved a bit.
- Adding another pointer to the main readme and particularly the stability section
- Clarifying repeatedly that while we document for transparency, you cannot rely on the implementation details
- Adding a bit more context re: security posture
I need to do a follow-up updating the "request handling" diagrams, we've made some slight changes since the last update.
=> clarify archeio docs

cmd/archeio/docs/testing.md, hack/make-rules/test.sh, hack/tools/require-coverage/main.go, pkg/net/cloudcidrs/internal/ranges2go/gen_test.go, pkg/net/cloudcidrs/internal/ranges2go/parse_gcp_test.go
Quick starting point to fix a long-standing TODO
I couldn't find a great off the shelf tool to simply enforce coverage levels from cover files. There are one or two tools but they tend to require also running the tests.
Go makes it very simple to parse coverage output, so I just wrote a tiny utility to require 100% coverage with some excluded packages. Primarily this ensures production archeio code maintains current coverage levels.
=> enforce code coverage levels

README.md, docs/mirroring/README.md, docs/mirroring/containerd.md, docs/mirroring/kubeadm.md
- readme link fixes originally in https://github.com/kubernetes/registry.k8s.io/pull/188
- clarify "infra budget"
- begin stubbing in mirroring guides to help people understand how to identify, mirror, and use mirrors with our images and associated tools and projects
We'll need to add a lot more to the mirroring guide, but I've tried to establish a reasonable structure and begin stubbing in a few I know about off the top of my head.
=> docs cleanup and start mirroring guides

docs/mirroring/README.md
following https://github.com/kubernetes-sigs/community-images/issues/47 we can point to a general tool to dump the running images in a cluster*
*excluding at least pause. getting that info from a running cluster portably would be quite a trick.
=> use community images to list images to mirror

docs/mirroring/README.md, docs/mirroring/containerd.md, docs/mirroring/kOps.md
trying to chip away at these in-between rollouts.
=> expand kOps and containerd mirroring guides

cmd/geranos/walkimages.go
GCR *does* store these in GCS.
I'm not sure why during development I thought these weren't showing up in the GCS bucket ...
These were previously copied in by the rclone script, not uploading them for new images is a regression, though a small one as they're not large and we'll just fallback to serving from AR.
```console
$ crane manifest k8s.gcr.io/pause:3.1 --platform=linux/amd64
{
"schemaVersion": 2,
"mediaType": "application/vnd.docker.distribution.manifest.v2+json",
"config": {
"mediaType": "application/vnd.docker.container.image.v1+json",
"size": 1609,
"digest": "sha256:da86e6ba6ca197bf6bc5e9d900febd906b133eaa4750e6bed647b0fbe50ed43e"
},
"layers": [
{
"mediaType": "application/vnd.docker.image.rootfs.diff.tar.gzip",
"size": 313363,
"digest": …
```
=> geranos: enable uploading config layers

docs/debugging.md
ref: https://github.com/kubernetes/registry.k8s.io/issues/211, https://github.com/kubernetes/registry.k8s.io/issues/174, https://github.com/kubernetes/registry.k8s.io/issues/138
TODO: maybe we can serve some code other than 403 from the app armor rules that *are* under Kubernetes's control (at least those should have a different reason message AFAICT)
=> add a debugging hint for GCP block

cloudbuild.yaml
we need to be able to build this quickly and even with a relatively cheap build the default cloudbuild machine type is single core.
custom sizes take longer to start but run faster.
=> improve image build times by increasing build machine size

cloudbuild.yaml, hack/make-rules/deploy.sh
Part of #76 
Auto-deploying staging from the production terraform will let us build confidence that:
1. The staging environment is actually representative of production, just with newer source code
2. We can safely auto-deploy production when changes merge in the k8s.io repo (not here)
We took a shortcut on the first point in particular I'd like to fix that.
I'm less concerned about auto deploy for 2) and to be honest we should have humans on hand to observe changes when we deploy to production considering the scope of potential breakage ...
Depends on https://github.com/kubernetes/k8s.io/pull/5081
=> deploy staging by overriding image version on terraform

hack/make-rules/lint.sh
should be ~no-op locally for warm development environments, but in CI it ensures module downloads happen prior to linting, so we don't factor that into the linter timeout. this also applies to new development environments that jump straight to `make lint`
=> avoid lint timeouts by downloading deps first

cloudbuild.yaml, hack/make-rules/deploy.sh
I think maybe the quota project is confusing `terraform apply` WRT APIs being enabled.
=> set default projects in cloudbuild

Makefile, cloudbuild.yaml, cmd/archeio/docs/testing.md, cmd/archeio/internal/e2e/e2e_test.go, hack/make-rules/deploy.sh, hack/make-rules/e2e-test-local.sh, hack/make-rules/e2e-test.sh, hack/make-rules/test.sh, hack/tools/go.mod, hack/tools/tools.go
This will allow us to quickly test the staging instance.
After this PR we'll automatically test some quick and cheap e2e tests immediately following staging deploys.
See code comments for why these are different from the integration tests.
This PR also cleans up tracking crane versions in two places
TODO: 
- Add a presubmit test that invokes `make e2e-test-local` (e2e tests against a local instance, for testing the tests) https://github.com/kubernetes/test-infra/pull/29249
- Add periodics on GCP and AWS that invoke `make e2e-test` and add that to the docs https://github.com/kubernetes/test-infra/pull/29249 for GCP
- Expand tests
=> add e2e tests in addition to cluster e2e testing

cmd/archeio/internal/app/buckets.go
depends on #206 
I haven't seen evidence that this is a problem yet, but it seems obviously problematic by inspection.
There is no default timeout on http.Client. We made a similar change for the listener.
It's possible to do more granular timeouts over e.g. dialing the connection, and other tuning, but this seems like the most important and simplest change.
/hold
Not sure if this counts as a bugfix ref: #181 as currently in practice we have very good response times and haven't seen this issue yet ... but it seems bound to happen.
=> set timeout for bucket HEAD client

cmd/archeio/internal/app/buckets.go, cmd/archeio/internal/app/buckets_integration_test.go, cmd/archeio/internal/app/buckets_test.go, cmd/archeio/internal/app/handlers.go, cmd/archeio/internal/app/handlers_test.go
\* will use more memory. should have better concurrency and less time spent locking.
The old implementation was written pretty quickly and overly "cleverly", attempting to dedupe the common base URL portion of the string.
We use so little memory right now that this simply isn't a concern, premature optimization :-)
However, we are almost certainly experiencing excessive contention over the blob cache RWMutex. `sync.Map` is more appropriate for append-only-cache type workloads.
Also: while we do want to configure the http client timeout, we don't want to share internal locking structures like the cookiejar, only the transport. A client that simply does not configure a transport gets the shared http.DefaultTransport anyhow.
=> simplify blob cache and improve performance*

cmd/archeio/internal/e2e/e2e_containerd_linux_test.go
See failures like https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/registry-sandbox-e2e-gcp/1650849058304036864
Simply due to containerd socket is not ready yet when we start pulling.
=> wait for containerd to be ready to avoid CI flakes

cmd/geranos/main.go, cmd/geranos/s3uploader.go, cmd/geranos/walkimages.go
1. Upload the manifests **after** uploading the layers, to record that we've already uploaded a given image digest to the bucket (with an added backup of the manifest contents instead of an empty key).
2. Skip re-uploading layers when we already have the manifest uploaded.
DOES NOT serve clients from the mirrored manifests.
Should produce a pretty large speedup on the second run. We'll be able to skip making any calls for these images except 1) bulk listing references in the registry 2) one S3 call per manifest to confirm it's already uploaded.
=> geranos: skip already uploaded images

Makefile
we can switch CI to this instead of `go run` + sourcing the go setup ...
=> add make target to build geranos

hack/make-rules/deploy.sh
fixes go attempting to use the module version and finding we don't have all the deps in go.sum
latest is fine, we're using an extremely stable command.
=> specify crane version in deploy.sh

hack/make-rules/images.sh
We shouldn't actually need to update this often, as it only contains cacerts, tzdata, and some static completely files (an /etc/passwd entry for root ... etc)
Better to pin it and avoid surprises / compromise.
https://github.com/GoogleContainerTools/distroless/blob/main/base/README.md
=> pin base image

cmd/archeio/internal/e2e/e2e_test.go
before:
```console
$ GOTOOLCHAIN=go1.22.1 make e2e-test
hack/make-rules/e2e-test.sh
+ /Users/bentheelder/go/src/k8s.io/registry.k8s.io/bin/gotestsum --junitfile=/Users/bentheelder/go/src/k8s.io/registry.k8s.io/bin/e2e-junit.xml -- -run '^TestE2E' ./cmd/archeio/internal/e2e
✖  cmd/archeio/internal/e2e (454ms)
=== Failed
=== FAIL: cmd/archeio/internal/e2e TestE2ECranePull (0.06s)
e2e_test.go:97: Failed to get "github.com/google/go-containerregistry/cmd/crane@latest": exit status 1
e2e_test.go:98: Output:
e2e_test.go:99: go: github.com/google/go-containerregistry/cmd/crane@latest: github.com/google/go-containerregistry@v0.20.3 requires go >= 1.23.0 (running go 1.22.1; GOTOOLCHAIN=go1.22.1)
DONE 1 tests, 1 failure in 0.883s
make: *** [e2e-test] Error 1
```
after:
```console
$ …
```
=> use auto go version when installing latest crane for e2e test

cmd/archeio/internal/e2e/e2e_containerd_linux_test.go, hack/make-rules/e2e-test.sh
We don't need to test every client and every version, we're just trying to make sure the registry isn't doing anything that breaks in the wild clients versus our read of the spec.
That said, since we _are_ testing with this client, we should really include the current major version.
=> add containerd 2.x to e2e tests, do not cache e2e tests

OWNERS
Riaan's handle has changed - https://github.com/kubernetes/org/pull/4938
Also Riaan is now on CNCF staff and no longer as active in this repo.
=> Drop old stale entry for Riaan as reviewer
